apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::798890232595:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RGJCQMACEGYN
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::798890232595:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-22T07:48:58Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2020-11-22T07:48:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1470"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 546cf38a-c469-429a-9472-03e142c2d4be
